[package]
name = "async-debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.33"
nix = {version= "0.30.1", features=["ptrace", "event", "signal"]}
oneshot = {version="0.2.1", features=["std", "async"]}
thiserror = "2.0.18"
tracing = "0.1.44"


[dev-dependencies]
tokio = {version = "1.48.0", features = ["sync", "macros", "rt", "time", "full", "tracing"]}
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }

[[ example ]]
name = "seize_test"
doc = false

[features]
default = ["mmap"]
mmap = ["nix/mman"]
